# Simple workflow for creating pages
name: run 11ty build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: create tag
        run: git tag --date
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: upload things
          path: _site
      - name: commit files
        run: |
              git add ./_site
              git config --global user.email "digital.services@ogs.ny.gov"
              git config --global user.name "Digital Services" 
              git commit -a -m "update can pages"
              git push

